language: csharp
sudo: required
mono: none
dotnet: 2.2.105
dist: xenial
before_install:
  - nvm install node
  - npm install -g yarn
deploy:
  - provider: script
    script: bash scripts/deploy.sh
    skip_cleanup: true
    on:
      tags: true
