language: csharp
sudo: required
mono: none
dotnet: 2.2.105
dist: xenial
before_install:
  - nvm install node
  - npm install -g yarn
script:
  - bash scripts/deploy.sh
  - bash scripts/docker.sh
  - bash scripts/nuget.sh
deploy:
  - provider: script
    script: if [[ "$TRAVIS_OS_BRANCH" == "dev" ]]; then bash scripts/docker.sh && bash scripts/nuget.sh          ; fi
    skip_cleanup: true
    on:
      branch: dev
      tags: true